// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessApi.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20210402182013_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "7104 6th Ave Tacoma WA 98406-1213",
                            Category = "Bakery",
                            Name = "The Art of Crunch",
                            PhoneNumber = "(253)-720-6180",
                            WebsiteUrl = "http://www.theartofcrunch.com/"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "5101 Yacht Club Rd, Tacoma WA 98407-3154",
                            Category = "Coffee",
                            Name = "The Dancing Goats® Coffee Bar Point Ruston",
                            PhoneNumber = "(253)-433-7926",
                            WebsiteUrl = "http://www.theartofcrunch.com/"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "c/o Serra House 6602 S Alaska St Tacoma WA 98408-1323",
                            Category = "Coffee",
                            Name = "The Coffee Oasis.com",
                            PhoneNumber = "(253)-328-6127",
                            WebsiteUrl = "https://thecoffeeoasis.com/"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "2200 Mildred St W University Place WA 98466-6041",
                            Category = "Bowling",
                            Name = "Narrows Plaza Bowl",
                            PhoneNumber = "(253)-565-1007",
                            WebsiteUrl = "https://www.narrowsplazabowl.com/"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "6323 6th Ave Tacoma WA 98406",
                            Category = "Bowling",
                            Name = "Tower Lanes",
                            PhoneNumber = "(253)-564-8853",
                            WebsiteUrl = "https://www.towerlanes.net/"
                        },
                        new
                        {
                            BusinessId = 6,
                            Address = "3806 N 26th St Tacoma WA 98407",
                            Category = "Bowling",
                            Name = "Chalet Bowl",
                            PhoneNumber = "(253)-752-5200",
                            WebsiteUrl = "https://www.chaletbowl.com//"
                        },
                        new
                        {
                            BusinessId = 7,
                            Address = "12505 Pacific Ave S Tacoma WA 98444",
                            Category = "Bowling",
                            Name = "Paradise Lanes Entertainment Center",
                            PhoneNumber = "(253)-537-6012",
                            WebsiteUrl = "https://www.bowlatparadise.com/"
                        },
                        new
                        {
                            BusinessId = 8,
                            Address = "902 129th St Ct E Tacoma WA 98445",
                            Category = "Bowling",
                            Name = "Double Dozen Bowling League",
                            PhoneNumber = "(253)-536-0514",
                            WebsiteUrl = ""
                        },
                        new
                        {
                            BusinessId = 9,
                            Address = "1911 Pacific Ave Tacoma WA 98402",
                            Category = "Coffee",
                            Name = "Anthem Coffee & Tea",
                            PhoneNumber = "(253)-572-9705",
                            WebsiteUrl = "https://myanthemcoffee.com/"
                        },
                        new
                        {
                            BusinessId = 10,
                            Address = "3918 6th Ave Tacoma WA 98406",
                            Category = "Coffee",
                            Name = "Valhalla Coffee Co.",
                            PhoneNumber = "(253)-761-5116",
                            WebsiteUrl = "http://www.valhallacoffee.com/"
                        },
                        new
                        {
                            BusinessId = 11,
                            Address = "2201 6th Ave Tacoma WA 98403",
                            Category = "Coffee",
                            Name = "Bluebeard Coffee Roasters",
                            PhoneNumber = "(253)-272-5600",
                            WebsiteUrl = "https://bluebeardcoffee.com/"
                        },
                        new
                        {
                            BusinessId = 12,
                            Address = "4918 Center St Tacoma WA 98409",
                            Category = "Coffee",
                            Name = "Gravity Coffee",
                            PhoneNumber = "(253)-447-8740",
                            WebsiteUrl = "http://gccoffee.com/"
                        },
                        new
                        {
                            BusinessId = 13,
                            Address = "1003 S 11th St Tacoma WA 98405",
                            Category = "Coffee",
                            Name = "Manifesto Coffee",
                            PhoneNumber = "(253)-503-7161",
                            WebsiteUrl = "http://www.manifestocoffeeroasters.com/"
                        },
                        new
                        {
                            BusinessId = 14,
                            Address = "817 Division Ave Tacoma WA 98403",
                            Category = "Coffee",
                            Name = "Cosmonaut Coffee Co",
                            PhoneNumber = "(253)-254-5052",
                            WebsiteUrl = "https://coffeetacoma.com/"
                        },
                        new
                        {
                            BusinessId = 15,
                            Address = "2601 N Proctor St #5225 Tacoma WA 98407",
                            Category = "Coffee",
                            Name = "Olympia Coffee Roasting",
                            PhoneNumber = "(253)-433-3279",
                            WebsiteUrl = "https://www.olympiacoffee.com/pages/proctor-tacoma"
                        },
                        new
                        {
                            BusinessId = 16,
                            Address = "4518 N Pearl St Tacoma WA 98407",
                            Category = "Coffee",
                            Name = "Coffeezaun Espresso",
                            PhoneNumber = "",
                            WebsiteUrl = "https://www.facebook.com/Coffeezaun/"
                        },
                        new
                        {
                            BusinessId = 17,
                            Address = "1901 Jefferson Ave # B Tacoma WA 98402",
                            Category = "Coffee",
                            Name = "Metro Coffee",
                            PhoneNumber = "(253)-627-8152",
                            WebsiteUrl = ""
                        },
                        new
                        {
                            BusinessId = 18,
                            Address = "Address: 1554 Market St #101, Tacoma, WA 98402",
                            Category = "Coffee",
                            Name = "Campfire coffee co.",
                            PhoneNumber = "",
                            WebsiteUrl = "https://www.welovecampfire.com/"
                        },
                        new
                        {
                            BusinessId = 19,
                            Address = "1102 A St #215 Tacoma WA 98402",
                            Category = "Coffee",
                            Name = "Lift Bridge Coffee",
                            PhoneNumber = "(253)-326-1354",
                            WebsiteUrl = "https://www.courthousesquaretacoma.com/lift-bridge-coffee"
                        },
                        new
                        {
                            BusinessId = 20,
                            Address = "919 N 2nd St Tacoma WA 98403",
                            Category = "Coffee",
                            Name = "Tacoma Java Company",
                            PhoneNumber = "(253)-292-9194",
                            WebsiteUrl = "http://tacoma-java-company.edan.io/"
                        },
                        new
                        {
                            BusinessId = 21,
                            Address = "764 Broadway Tacoma WA 98402",
                            Category = "Coffee",
                            Name = "Bostwick Cafe",
                            PhoneNumber = "(253)-302-5296",
                            WebsiteUrl = "https://www.bostwickcafe.com/"
                        },
                        new
                        {
                            BusinessId = 22,
                            Address = "1322 Fawcett Ave Tacoma WA 98402",
                            Category = "Coffee",
                            Name = "Honey Coffee + Kitchen",
                            PhoneNumber = "(253)-507-7289",
                            WebsiteUrl = "https://www.almamatertacoma.com/honey-cafe"
                        },
                        new
                        {
                            BusinessId = 23,
                            Address = "3121 S 38th St Tacoma WA 98409",
                            Category = "Coffee",
                            Name = "Martin Henry Espresso",
                            PhoneNumber = "(253)-284-0523",
                            WebsiteUrl = "https://www.martinhenryespresso.com/"
                        },
                        new
                        {
                            BusinessId = 24,
                            Address = "1102 S Yakima Ave, Tacoma, WA 98405",
                            Category = "Coffee",
                            Name = "Hilltop Coffee Bar & Cafe",
                            PhoneNumber = "(253)-272-0112",
                            WebsiteUrl = "https://hilltopcoffeebarcafe.com/"
                        },
                        new
                        {
                            BusinessId = 25,
                            Address = "2716 N 21st St Tacoma WA 98406",
                            Category = "Coffee",
                            Name = "Lander Coffee",
                            PhoneNumber = "(253)-625-7843",
                            WebsiteUrl = "https://www.landercoffee.com//"
                        },
                        new
                        {
                            BusinessId = 26,
                            Address = "4020 S 56th St Tacoma WA 98409",
                            Category = "Coffee",
                            Name = "Fox Hollow Coffee Shop",
                            PhoneNumber = "(253)-475-0933",
                            WebsiteUrl = "http://fox-hollow-coffee-shop.edan.io/"
                        },
                        new
                        {
                            BusinessId = 27,
                            Address = " 5107 Grand Loop Tacoma WA 98407",
                            Category = "Coffee",
                            Name = "Jewel Box Cafe",
                            PhoneNumber = "(253)-752-4863",
                            WebsiteUrl = "https://www.jewelboxcafeatruston.com/"
                        },
                        new
                        {
                            BusinessId = 28,
                            Address = "1114 M.L.K. Jr Way Tacoma WA 98405",
                            Category = "Coffee",
                            Name = "Red Elm Cafe",
                            PhoneNumber = "(253)-327-1791",
                            WebsiteUrl = "https://red-elm-cafe.square.site/"
                        },
                        new
                        {
                            BusinessId = 29,
                            Address = "6450 Tacoma Mall Blvd Tacoma WA 98409",
                            Category = "Coffee",
                            Name = "Bella Latee",
                            PhoneNumber = "(253) 472-1975",
                            WebsiteUrl = "http://bella-latte.edan.io/"
                        },
                        new
                        {
                            BusinessId = 30,
                            Address = "9115 S Tacoma Way Tacoma WA 98499",
                            Category = "Coffee",
                            Name = "Coffee Kitchen",
                            PhoneNumber = "(253)-588-4191",
                            WebsiteUrl = ""
                        },
                        new
                        {
                            BusinessId = 31,
                            Address = "618 N 1st St, Tacoma, WA 98403",
                            Category = "Coffee",
                            Name = "North Slope Coffee",
                            PhoneNumber = "(253) 383-7277",
                            WebsiteUrl = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
